import { CompletionItemKind } from "vscode-languageserver";

export interface IRslBuiltinDefinition {
    name: string;
    kind: CompletionItemKind;
    typeName: string;
    signature?: string;
    summary?: string;
    insertText?: string;
    children?: readonly IRslBuiltinDefinition[];
}

/*
 * Каталог хранит только факты, необходимые IDE: имена, сигнатуры, типы и
 * короткие собственные описания. Текст руководства и ссылки на него сюда не
 * копируются. Массив создаётся один раз при загрузке language server.
 */
const STANDARD_PROCEDURE_SIGNATURES = [
    "GetInt (id [, prompt, len [, hide] ])",
    "GetDouble (id [, prompt, len [, hide [, pos ] ] ])",
    "GetMoney (id [, prompt, len [, hide] [, pos]])",
    "GetNumeric (id [, prompt, len [, hide [, pos] ] ])",
    "GetString (id [, prompt, len [, hide] ])",
    "GetStringR (id [, prompt, len [, hide] ])",
    "GetTime(id [, prompt [, hide ] ])",
    "GetDate (id [, prompt [, hide] ])",
    "GetTRUE (id [, prompt ])",
    "Print (...)",
    "PrintGlobs (...)",
    "PrintFiles (...)",
    "PrintLn",
    "PrintLocs (...)",
    "PrintModule (modName:String)",
    "PrintProps (object)",
    "PrintRefs (ob: Object)",
    "PrintStack (...)",
    "PrintSymModule (symbolName:String)",
    "Message",
    "SetOutput ([ string ] [, bool ])",
    "SetColumn (integer)",
    "FlushColumn",
    "ClearColumn",
    "SetDefPrec (integer)",
    "SetOutHandler (NameMacro)",
    "GetPRNInfo ([escSeq:String, banner:String, frmFeed:Bool]) : String",
    "SetPRNInfo (prnName: String [, escSeq: String, banner: String, frmFeed:Bool ])",
    "ValType (val)",
    "Double (val)",
    "DoubleL (val)",
    "Int (val)",
    "String (val {, val})",
    "Money (val)",
    "MkStr (val1, val2)",
    "Floor (val)",
    "Asize (val [, newsize])",
    "Date (...)",
    "DateSplit (date, day, mon, year)",
    "Time (...)",
    "TimeSplit (time, hour, min, sec)",
    "DtTm (date, time)",
    "DtTmSplit (d, dt, tm)",
    "RubToStr (money [, rub, kop [, full ]], kol)",
    "RubToStrAlt (money, [rub, kop, ] kol)",
    "CurToStrAlt (money [, rub, kop ], ISO, kol)",
    "MonName (mon)",
    "NumToStr (val, n1:String, n2:String, n3:String, isMan:Bool, prec:Integer) : String",
    "SetAutoMoneyFloor (auto:Bool):bool",
    "Round (val:Variant [, pos:Integer] , [round:Integer]):Money",
    "MakeDouble (p1:Integer, p2:Integer, p3:Integer):Double",
    "MakeMoney (p1:Integer, p2:Integer, p3:Integer):Money",
    "SplitMoney (mn:Money, p1:@Integer, p2:@Integer, p3:@Integer)",
    "StrLen (string)",
    "Index (srcStr:String, fnd:String [, startPos:Integer]):Integer",
    "StrBrk (string1, string2)",
    "StrIsNumber(str:String):Bool",
    "SubStr (string, integer1 [, integer2])",
    "StrSet (string1, integer, string2)",
    "Trim (string)",
    "StrSplit (string, array, len [, len_first] [, minseg])",
    "StrSplit2 (source:String, len:Integer [, len_first:Integer] [, minseg:Integer]) : TArray",
    "StrUpr (string [,len])",
    "StrLwr (string [, len])",
    "CodeFor (string)",
    "StrFor (number)",
    "StrSubst (sourse, strToFind, strToReplace)",
    "ToOEM (string [, mode])",
    "ToANSI (string [, mode])",
    "GetParm (num, var)",
    "IsOutParm (num:Integer):Bool",
    "SetParm (num, expression)",
    "Parmcount ()",
    "Run (prog, parm, init, finish:String])",
    "CallRemoteRsl (fileName [, procName [, parm1, parm2, ...]])",
    "Menu (array [, prompt] [, head] [, x] [, y] [, n])",
    "RunMenu (menuName, procName | procAddr [, lbrName])",
    "AddScroll (dlg:TRecHandler, data:Object [, numCol:Integer, colArray:TArray ,",
    "RunDialog (dlg:TRecHandler [, proc:Variant]):Bool",
    "DisableValidation (dlg:Variant, id:Integer)",
    "UpdateFields (dlg:TRecHandler [, id:Integer])",
    "SetFocus (dlg:TRecHandler, id:Integer)",
    "MsgBox (mes)",
    "DisableFields (dlg:TRecHandler [, id:Integer])",
    "EnableFields (dlg:TRecHandler [, id:Integer])",
    "SetTimer (dlg:TRecHandler [, timeOut:Integer, set:Bool])",
    "MsgBoxEx (val:Variant [, flags:Integer, defInd:Integer, title:String, statLn:String ])",
    "SetScroll (FILE, { DlgName, FileName } ...)",
    "FindRow (dlg, id)",
    "FindCol (dlg, id)",
    "FillDown (dlg, pos)",
    "FillUp (dlg, pos)",
    "SetDlgFields (dlg, row)",
    "ScrollMes (dlg, cmd, id, key)",
    "UserFill (dlg)",
    "AddMultiAction (rs:Object, key:Integer):Bool",
    "GetMultiCount (rs:Object):Integer",
    "GoToScroll (obj:Object)",
    "RunScroll (data:Object, numCol:Integer, colInfo:TArray, uniqName, proc:Variant,",
    "UpdateScroll (obj:Object, mode:Integer)",
    "GetScrollFieldValue(numfld:Integer, value:Undef):Bool",
    "SetScrollFieldValue(numfld:Integer, newvalue:Undef, [strlen:Integer]):Bool",
    "IsScrollEditMode():Bool",
    "Trace (...)",
    "DebugBreak",
    "ConvertDDF (defName:String, outDir:String):Bool",
    "CopyTblDef (inDef:String, outDef:String, inStruct:String, outStruct:String):Bool",
    "ExistFile (string [, integer])",
    "Open (fid, name:String, encode:String, fatal:Bool, eolType:Integer) : Bool",
    "Close (id)",
    "ClearStructs",
    "Create (id [, filename] [, isTable:Bool] [, isP:Bool])",
    "Clone (id [, filename] [, isTable:Bool] [, isP:Bool])",
    "ViewFile (id, name [, edit])",
    "DelFile (string)",
    "DropTable (string)",
    "Next (id [, integer])",
    "Prev (id)",
    "ReWind (id)",
    "Insert (id [, string | size] [, integer] [, bool])",
    "Update (id [, size] [, bool])",
    "Delete (id, bool)",
    "GetPos (id)",
    "GetDirect (id [, recpos])",
    "GetEQ (id)",
    "GetGT (id)",
    "GetGE (id)",
    "GetLT (id)",
    "GetLE (id)",
    "SetRecordAddr (recId, fileId [, ind] [, offset] [, fix])",
    "PackVarBuff (file [, size])",
    "UnPackVarBuff (file)",
    "GetRecordSize (id)",
    "GetVarSize (id)",
    "FileName (id)",
    "NRecords (id [, par:Bool])",
    "FldNumber (id)",
    "FldName (id, number)",
    "FldIndex (id, string)",
    "FldOffset (id, string | number)",
    "ClearRecord (id)",
    "SetBuff (id, addr)",
    "Copy (id1, id2 [, flag:Integer])",
    "CopyBlob ()",
    "KeyNum (id [, newkey])",
    "SetDelim (symbol, space)",
    "Status (...)",
    "ProcessTrn (TrnType:Integer, MacroName:String, Variant [, file1:File] [, file2:File] [,",
    "LoopInTrn (val)",
    "AbortTrn()",
    "SelectFile (file [, mask, head], sort, term)",
    "SelectFolder (folder [, mask, head, ] term)",
    "NeedFreeDB ()",
    "WriteBlob (file, value)",
    "ReadBlob (file, value)",
    "CopyFile (src:String, dst:String [, ind:Bool [, indHeading:String]]) : Bool",
    "RenameFile (src:String, dst:String) : Bool",
    "RemoveFile (src:String) : Bool",
    "ExistDir(name:String):Integer",
    "MakeDir (name:String) : Bool",
    "RemoveDir (name:String) : Bool",
    "GetCurDir ([isRemote:Bool]) : String",
    "SplitFile (pathName: String [, name: String [, ext: String ] ]): String",
    "MergeFile (dirName: String ,name: String [, ext: String ]): String",
    "FindPath (name: String [, dirList: String [, defExt: String [, curDir: Bool ] ] ]):",
    "GetSysDir ([ ndir: Integer ]): String",
    "GetIniFileValue (iniFileName:String, keyName:String):String",
    "GetFileInfo (src:String [, dt:@Date, tm:@Time, size:@Integer, path:@String]) : Bool",
    "ActiveX (mon:String, const=1):Object",
    "ClassKind (obj:Object [, mask:Integer):Integer",
    "GenClassName (obj)",
    "GenAttach (id, methodName, macroName | macroAddr)",
    "GenObject (className [ , parm1, parm2, ...])",
    "GenRun (ob, methodName [, par1, par2, ...])",
    "GenSetProp (ob, propName, val)",
    "GenGetProp (ob, propName)",
    "GetObjProps (obj:Object, [CaseSensitive:Bool]):TArray",
    "GetObjMethods (obj:Object, [CaseSensitive:Bool]):TArray",
    "IsEqClass (className, obj)",
    "GenPropID (obj, propName)",
    "R2M (obj:Object, name:String) : MethodRef",
    "CallR2M (oPtr:MethodRef [, par1, par2,...]) : Variant",
    "GenNumProps (obj:Object) : Integer",
    "ClrRmtOnRelease (proxy:Object) : Bool",
    "GetNamedChanel (name:String) : Object",
    "InitProgress (maxRecord:Integer [, msg:String, head:String])",
    "UseProgress (record)",
    "RemProgress",
    "BegAction ([tm:Integer, text:String, canClose:Bool])",
    "EndAction (tm:Integer)",
    "CheckBits (n1:Integer, n2:Integer):Integer",
    "DateShift (inData:Date [, nDay:Integer] [, nMon:Integer] [, nYear:Integer]):Date",
    "ExecMacro (string,.....)",
    "ExecMacro2 (string, .....)",
    "ExecMacroFile (Module [, ProcName [, Parm1,Parm2, ...] ])",
    "ExecMacroModule (codeStr:String [, macroName, par1, par2, ...])",
    "ReplaceMacro (string1, [ string2 ])",
    "ExecExp (string)",
    "GCollect (ncol:@Integer):Integer",
    "GetCallStack ()",
    "GetEnv (string)",
    "GetMemAddrFrom (obj:Variant):MemAddr",
    "GetUIMode (...)",
    "InstLoadModule (moduleName:String):Bool",
    "IsWeakRef (obj:Object):Bool",
    "WriteByte (stream:Object, byte:Integer):Bool",
    "ReadByte (stream:Object, byte:@Integer):Bool",
    "RunError ([ mes:String] [, userObj:Variant])",
    "Exit ([code:Integer] [, mes:String])",
    "SetExitFlag (code:Integer)",
    "MemSize()",
    "Version()",
    "CurrentLine ([ line ])",
    "UserNumber ()",
    "Random ([ integer ])",
    "SetDefMoneyPrec (newVal:Integer):Integer",
    "ShowDictError (show:Bool):Bool",
    "ShowRSCOMError (obj:TRsComErr)",
    "StartProg (fileName:String [, cmdLine:String ] [, detached:Bool]):Integer",
    "StrongRef (par:Object):Object",
    "SysGetProperty (key:String):String",
    "SysPutProperty (key:String, val:String):Bool",
    "System (Number:Integer, CodeFor:Integer|Type:String [, CmdArgs:String])",
    "IsStandAlone",
    "TestEvent ([pause])",
    "AddEvent (key:Integer)",
    "IsGUI",
    "ErrPrint (...)",
    "ErrBox (str:TArray [,caption:String, flags:Integer) : Integer",
    "ModuleFileName ([moduleName:String] [, moduleType:@Integer]):String",
    "ModuleName ([symbolName:string]):string",
    "CmdArgs (...)",
    "GetUserName (...)",
    "IsSQL (...)",
    "UnderRCWHost (...)",
    "GetLocaleInfo (id:Integer, code:Integer [, isLocal:Bool]) : String",
    "GetLangId (id:Integer [, isLocal:Bool]) : Integer",
    "ZeroValue (valtp:Integer):Variant",
    "StartShellProgram (fileName:Char):Integer",
] as const;

const RETURN_TYPES: Readonly<Record<string, string>> = Object.freeze({
    getint: "Bool",
    getdouble: "Bool",
    getmoney: "Bool",
    getnumeric: "Bool",
    getstring: "Bool",
    getstringr: "Bool",
    gettime: "Bool",
    getdate: "Bool",
    gettrue: "Bool",
    valtype: "Integer",
    double: "Double",
    doublel: "DoubleL",
    int: "Integer",
    string: "String",
    money: "Money",
    mkstr: "String",
    floor: "Integer",
    asize: "Integer",
    date: "Date",
    time: "Time",
    dttm: "DateTime",
    rubtostr: "String",
    rubtostralt: "String",
    curtostralt: "String",
    monname: "String",
    numtostr: "String",
    round: "Money",
    makedouble: "Double",
    makemoney: "Money",
    strlen: "Integer",
    index: "Integer",
    strbrk: "Integer",
    strisnumber: "Bool",
    substr: "String",
    strset: "String",
    trim: "String",
    strsplit2: "TArray",
    strupr: "String",
    strlwr: "String",
    codefor: "Integer",
    strfor: "String",
    strsubst: "String",
    isoutparm: "Bool",
    parmcount: "Integer",
    existfile: "Bool",
    next: "Bool",
    prev: "Bool",
    rewind: "Bool",
    insert: "Bool",
    update: "Bool",
    delete: "Bool",
    geteq: "Bool",
    getgt: "Bool",
    getge: "Bool",
    getlt: "Bool",
    getle: "Bool",
    nrecords: "Integer",
    fldnumber: "Integer",
    fldname: "String",
    fldindex: "Integer",
    fldoffset: "Integer",
    filename: "String",
    getrecordsize: "Integer",
    getvarsize: "Integer",
    existdir: "Integer",
    makedir: "Bool",
    removedir: "Bool",
    getcurdir: "String",
    splitfile: "String",
    mergefile: "String",
    findpath: "String",
    getsysdir: "String",
    getinifilevalue: "String",
    getfileinfo: "Bool",
    activex: "Object",
    classkind: "Integer",
    genclassname: "String",
    genobject: "Object",
    iseqclass: "Bool",
    execmacro: "Variant",
    execmacro2: "Variant",
    execmacrofile: "Variant",
    execmacromodule: "Variant",
    execexp: "Variant",
    getcallstack: "TArray",
    getenv: "String",
    getuimode: "Integer",
    isweakref: "Bool",
    random: "Integer",
    modulefilename: "String",
    modulename: "String",
    cmdargs: "TArray",
    getusername: "String",
    isgui: "Bool",
    issql: "Bool",
    getlocaleinfo: "String",
    getlangid: "Integer",
    zerovalue: "Variant"
});

const SUMMARIES: Readonly<Record<string, string>> = Object.freeze({
    getint: "Вводит значение Integer.",
    getdouble: "Вводит значение Double.",
    getmoney: "Вводит значение Money.",
    getstring: "Вводит строковое значение.",
    print: "Выводит переданные значения.",
    println: "Выводит значения и перевод строки.",
    valtype: "Возвращает код типа значения.",
    strlen: "Возвращает длину строки.",
    substr: "Возвращает фрагмент строки.",
    trim: "Удаляет крайние пробелы.",
    strsubst: "Заменяет подстроки.",
    execmacro: "Вызывает макропроцедуру по имени.",
    execmacrofile: "Вызывает макропроцедуру из файла.",
    runerror: "Повторно генерирует текущую ошибку.",
    msgbox: "Показывает сообщение.",
    debugbreak: "Передаёт управление отладчику."
});

const CLASS_DEFINITIONS: readonly IRslBuiltinDefinition[] = [
    classDef("TArray", "Динамический массив RSL.", [
        property("Size", "Integer", "Размер массива."),
        property("MarshalByVal", "Bool", "Режим передачи массива."),
        method("Sort(callback, data): Bool", "Сортирует элементы массива.")
    ]),
    classDef("TRslError", "Информация об ошибке RSL.", [
        property("Code", "Integer", "Код ошибки."),
        property("Message", "String", "Текст ошибки."),
        property("Module", "String", "Имя модуля."),
        property("Line", "Integer", "Номер строки."),
        property("AxCode", "Integer", "Код ошибки ActiveX."),
        property("AxMes", "String", "Текст ошибки ActiveX."),
        property("err", "Object", "Пользовательская ошибка.")
    ]),
    classDef("TBFile", "Таблица или файл базы данных.", [
        method("AddFilter(cond: String): Bool", "Добавляет фильтр."),
        method("DropFilter(): Bool", "Удаляет фильтр."),
        method("GetFldInfo(): TArray", "Возвращает сведения о полях."),
        method("GetKeyInfo(): TArray", "Возвращает сведения о ключах."),
        method("Clear(): Bool", "Очищает буфер записи."),
        method("Delete([flag: Bool]): Bool", "Удаляет текущую запись."),
        method("GetDirect([recpos: Integer]): Bool", "Читает запись по позиции."),
        method("GetPos(): Integer", "Возвращает позицию записи."),
        method("GetEQ(): Bool", "Ищет запись с равным ключом."),
        method("GetGE(): Bool", "Ищет запись с не меньшим ключом."),
        method("GetGT(): Bool", "Ищет запись с большим ключом."),
        method("GetLE(): Bool", "Ищет запись с не большим ключом."),
        method("GetLT(): Bool", "Ищет запись с меньшим ключом."),
        method("Insert(...): Bool", "Добавляет запись."),
        method("Next(): Bool", "Переходит к следующей записи."),
        method("Prev(): Bool", "Переходит к предыдущей записи."),
        method("Rewind(): Bool", "Сбрасывает позицию чтения."),
        method("Update(...): Bool", "Обновляет текущую запись."),
        method("ReadBlob(value): Bool", "Читает BLOB."),
        method("WriteBlob(value): Bool", "Записывает BLOB."),
        method("SetRecordAddr(...): Bool", "Связывает буфер записи."),
        method("PackVarBuff([size: Integer]): Bool", "Упаковывает переменный буфер."),
        method("UnPackVarBuff(): Bool", "Распаковывает переменный буфер."),
        property("Rec", "Record", "Текущая запись."),
        property("KeyNum", "Integer", "Номер текущего ключа."),
        property("NRecords", "Integer", "Количество записей."),
        property("FileName", "String", "Имя файла."),
        property("RecSize", "Integer", "Размер записи."),
        property("VarSize", "Integer", "Размер переменной части.")
    ]),
    classDef("TRecHandler", "Объект записи или диалога.", [
        property("Rec", "Record", "Связанная запись."),
        method("SetRecordAddr(file, ind, offs, isFix): Bool")
    ]),
    classDef("RsdEnvironment", "Окружение доступа к данным.", [
        property("ErrorCount", "Integer", "Количество ошибок."),
        property("Error", "RsdError", "Ошибка по индексу."),
        method("Open([driver], [library]): Bool"),
        method("Close(): Bool"),
        method("ClearErrors(): Bool")
    ]),
    classDef("RsdConnection", "Соединение с источником данных.", [
        property("Environment", "RsdEnvironment"),
        property("State", "Integer"),
        method("Open(): Bool"),
        method("Close(): Bool"),
        method("BeginTrans(): Bool"),
        method("CommitTrans(): Bool"),
        method("RollbackTrans(): Bool"),
        method("IsInTrans(): Bool")
    ]),
    classDef("RsdCommand", "Команда источника данных.", [
        property("Connection", "RsdConnection"),
        property("CommandText", "String"),
        property("CommandType", "Integer"),
        property("CursorType", "Integer"),
        property("ParamCount", "Integer"),
        property("Value", "Variant"),
        method("Execute([parm1, ...]): RsdRecordset"),
        method("AddParam(name: String, [dir: Integer], [val], [len: Integer]): RsdParameter"),
        method("DeleteParam(indexOrName): Bool"),
        method("RefreshParams(): Bool")
    ]),
    classDef("RsdRecordset", "Набор данных RSD.", [
        property("BOF", "Bool"),
        property("EOF", "Bool"),
        property("FieldCount", "Integer"),
        property("RecordCount", "Integer"),
        property("Fld", "RsdField"),
        property("Value", "Variant"),
        method("Open(): Bool"),
        method("Close(): Bool"),
        method("MoveNext(): Bool"),
        method("MovePrev(): Bool"),
        method("MoveFirst(): Bool"),
        method("MoveLast(): Bool"),
        method("Move(numRec, moveDirect): Bool"),
        method("AddNew(): Bool"),
        method("Edit(): Bool"),
        method("Update(): Bool"),
        method("CancelEdit(): Bool"),
        method("Delete(): Bool")
    ]),
    classDef("RsdError", "Ошибка RSD.", [
        property("Code", "Integer"),
        property("Message", "String"),
        property("State", "String")
    ]),
    classDef("RsdField", "Поле набора данных.", [
        property("Name", "String"),
        property("Type", "Integer"),
        property("Value", "Variant"),
        property("Size", "Integer"),
        method("Read(out, [count]): Bool"),
        method("Write(value, [count]): Bool")
    ]),
    classDef("RsdParameter", "Параметр команды RSD.", [
        property("Name", "String"),
        property("Direction", "Integer"),
        property("Type", "Integer"),
        property("Value", "Variant"),
        property("Size", "Integer")
    ]),
    classDef("TStream", "Двоичный поток.", [
        method("Write(from, [type], [size], [decPoint]): Bool"),
        method("Read(out, [type], [size], [decPoint]): Bool"),
        method("Write2(from: Object): Bool"),
        method("Read2(to: Object): Bool"),
        method("WriteVal(from): Bool"),
        method("ReadVal(to): Bool"),
        method("Copy(from: Object, [numBytes: Integer]): Bool"),
        method("SetPos(pos: Integer, [from: Integer]): Bool"),
        method("GetPos(): Integer"),
        method("SetSize(size: Integer): Bool"),
        method("GetSize(): Integer"),
        method("Flush(): Bool")
    ]),
    classDef("TStreamDoc", "Текстовый поток.", [
        property("Str", "String", "Последняя прочитанная строка."),
        method("WriteLine(value: String): Bool"),
        method("ReadLine(result: @String): Bool"),
        method("WriteVal(from): Bool"),
        method("ReadVal(to): Bool"),
        method("Flush(): Bool")
    ]),
    classDef("TDirList", "Список файлов и каталогов.", [
        property("Count", "Integer"),
        method("FDate(index: Integer): Date"),
        method("FTime(index: Integer): Time"),
        method("IsCopy(index: Integer): Bool"),
        method("IsDel(index: Integer): Bool"),
        method("IsDir(index: Integer): Bool"),
        method("Name(index: Integer): String"),
        method("Size(index: Integer): Integer"),
        method("SizeEx(index: Integer): Integer"),
        method("Copy(srcMask: String, attr: String, dstDir: String, ...): Bool"),
        method("List(mask: String, [attr: String], [newSizeMode: Bool]): Bool"),
        method("Remove(mask: String, [attr: String]): Bool"),
        method("Sort([sortBy: Integer], [dirFirst: Bool]): Bool")
    ]),
    classDef("TRslEvHandler", "Обработчик событий.", [
        property("EvSource", "Object"),
        property("TypeLib", "Object"),
        method("SetHandler(pref, proc, id): Bool"),
        method("RemHandler(pref, id): Bool"),
        method("Raise(...): Bool")
    ]),
    classDef("RslTimer", "Таймер RSL.", [
        method("SetTimer(timeout: Integer, id: Integer, handler, [isSys: Bool]): Bool"),
        method("RemTimer(id: Integer): Bool")
    ]),
    classDef("TRepForm", "Форма отчёта."),
    classDef("TPattFieldR", "Поле шаблона отчёта."),
    classDef("ToolsDataAdapter", "Источник данных интерфейса."),
    classDef("TRslChanel", "Канал RSCOM."),
    classDef("TRcwSite", "Контекст RSCOM."),
    classDef("TRsAxServer", "Сервер ActiveX."),
    classDef("TRcwHost", "Хост RSCOM."),
    classDef("TClrHost", "Хост .NET."),
    classDef("TJavaHost", "Хост Java."),
    classDef("TJavaObj", "Объект Java.")
];

export const RSL_STANDARD_LIBRARY: readonly IRslBuiltinDefinition[] =
    Object.freeze([
        ...CLASS_DEFINITIONS,
        ...STANDARD_PROCEDURE_SIGNATURES.map(procedureFromSignature)
    ]);

function procedureFromSignature(signature: string): IRslBuiltinDefinition {
    const name = signature.match(/^([^\s(]+)/)?.[1] || signature;
    const normalizedSignature = balancedSignature(signature)
        ? signature
        : `${name}(...)`;
    const explicitType = normalizedSignature
        .match(/\)\s*:\s*(@?[\wА-Яа-яЁё]+)/u)?.[1];
    const key = name.toLowerCase();
    return {
        name,
        kind: CompletionItemKind.Function,
        typeName: explicitType || RETURN_TYPES[key] || "Variant",
        signature: normalizedSignature,
        summary: SUMMARIES[key] || "Встроенная процедура RSL."
    };
}

function balancedSignature(value: string): boolean {
    const stack: string[] = [];
    const pairs: Readonly<Record<string, string>> = {
        ")": "(",
        "]": "[",
        "}": "{"
    };
    for (const character of value) {
        if (character === "(" || character === "[" || character === "{") {
            stack.push(character);
        } else if (character in pairs && stack.pop() !== pairs[character]) {
            return false;
        }
    }
    return stack.length === 0;
}

function classDef(
    name: string,
    summary: string,
    children: readonly IRslBuiltinDefinition[] = []
): IRslBuiltinDefinition {
    return {
        name,
        kind: CompletionItemKind.Class,
        typeName: name,
        signature: `${name}(...)`,
        summary,
        children
    };
}

function method(
    signature: string,
    summary = "Метод стандартного класса."
): IRslBuiltinDefinition {
    const name = signature.match(/^([^\s(]+)/)?.[1] || signature;
    const typeName = signature.match(/\)\s*:\s*(@?[\wА-Яа-яЁё]+)/u)?.[1] ||
        "Variant";
    return {
        name,
        kind: CompletionItemKind.Method,
        typeName,
        signature,
        summary
    };
}

function property(
    name: string,
    typeName: string,
    summary = "Свойство стандартного класса."
): IRslBuiltinDefinition {
    return {
        name,
        kind: CompletionItemKind.Property,
        typeName,
        summary
    };
}
